version: "3"
services:
  pid_tuning:
    image: mp4sini/pid_tuning
    restart: on-failure
    volumes:
      - "./data/experiments/pid_tuning/setup:/home/data/"
    command:
      - /bin/bash
      - -c
      - |
        chmod +x run_tuning.sh && \
        ./run_tuning.sh

  smarter_robustness:
    image: mp4sini/smarter_robustness
    restart: on-failure
    volumes:
      - "./data/experiments/robustness:/home/statistics/"
    command:
      - /bin/bash
      - -c
      - |
        sudo apt install dos2unix
        dos2unix run_evaluation.sh
        chmod +x run_evaluation.sh && \
        ./run_evaluation.sh